const availableVoices = [
  "UK English Female",
  "UK English Male",
  "US English Female",
  "US English Male",
  "Arabic Male",
  "Arabic Female",
  "Armenian Male",
  "Australian Female",
  "Australian Male",
  "Bangla Bangladesh Female",
  "Bangla Bangladesh Male",
  "Bangla India Female",
  "Bangla India Male",
  "Brazilian Portuguese Female",
  "Chinese Female",
  "Chinese Male",
  "Chinese (Hong Kong) Female",
  "Chinese (Hong Kong) Male",
  "Chinese Taiwan Female",
  "Chinese Taiwan Male",
  "Czech Female",
  "Danish Female",
  "Deutsch Female",
  "Deutsch Male",
  "Dutch Female",
  "Dutch Male",
  "Estonian Male",
  "Filipino Female",
  "Finnish Female",
  "French Female",
  "French Male",
  "French Canadian Female",
  "French Canadian Male",
  "Greek Female",
  "Hindi Female",
  "Hindi Male",
  "Hungarian Female",
  "Indonesian Female",
  "Indonesian Male",
  "Italian Female",
  "Italian Male",
  "Japanese Female",
  "Japanese Male",
  "Korean Female",
  "Korean Male",
  "Latin Male",
  "Nepali",
  "Norwegian Female",
  "Norwegian Male",
  "Polish Female",
  "Polish Male",
  "Portuguese Female",
  "Portuguese Male",
  "Romanian Female",
  "Russian Female",
  "Sinhala",
  "Slovak Female",
  "Spanish Female",
  "Spanish Latin American Female",
  "Spanish Latin American Male",
  "Swedish Female",
  "Swedish Male",
  "Tamil Female",
  "Tamil Male",
  "Thai Female",
  "Thai Male",
  "Turkish Female",
  "Turkish Male",
  "Ukrainian Female",
  "Vietnamese Female",
  "Vietnamese Male",
  "Afrikaans Male",
  "Albanian Male",
  "Bosnian Male",
  "Catalan Male",
  "Croatian Male",
  "Esperanto Male",
  "Icelandic Female",
  "Latvian Male",
  "Macedonian Male",
  "Moldavian Female",
  "Montenegrin Male",
  "Serbian Male",
  "Serbo-Croatian Male",
  "Swahili Male",
  "Welsh Male",
  "Fallback UK Female"
];
